### ISSUE TITLE
Error on Copy activity for API Jon to Blob

### ISSUE THREAD

**Issue by iLikeAzureSQL** [Mmodarre/AzureDataFactoryHOL#12]
https://github.com/Mmodarre/AzureDataFactoryHOL/blob/master/Lab-guide/03-Copy_Activity_Parameters_Debug_and_Publishing/README.md

I was able to to follow all the way through till the last copy activity where it's failing 
with error :
{
    "errorCode": "2200",
    "message": "ErrorCode=SchemaMappingFailedInHierarchicalToTabularStage,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to process hierarchical to tabular stage, error message: One or more errors occurred.,Source=Microsoft.DataTransfer.ClientLibrary,'",
    "failureType": "UserError",
    "target": "SmartFoodsCustomersToBlob",
    "details": []
}

![image](https://user-images.githubusercontent.com/16943754/82483599-7f001700-9a8d-11ea-9885-1a5ac5e1f6c2.png)

Need to mention that accessing the source data via API is not a problem, I verified that by postman call.
![image](https://user-images.githubusercontent.com/16943754/82484919-7d375300-9a8f-11ea-8286-8c0d2781caff.png)

**Comment by Mmodarre** [comment]
Not exactly sure what is going wrong here. When I try the pipeline succeeds. 
![image](https://user-images.githubusercontent.com/23395096/82507388-71a66380-9b45-11ea-9172-7abd882cd699.png)
Could you please share the settings tab and mapping tab of your copy activity.

**Comment by tanmoycuat** [comment]
I am having a peculiar problem, the file is being saved only to one destination file not as per the sink configuration.

![image](https://user-images.githubusercontent.com/47568628/82747068-63f61580-9db3-11ea-838e-05d34bfd2651.png)


![image](https://user-images.githubusercontent.com/47568628/82747034-21ccd400-9db3-11ea-93c7-f35c698cc8ca.png)

Any help why there is an issue with the same file name. I should have a file with dates as a postfix.

**Comment by Mmodarre** [comment]
I suggest you double check your dataset and linked service to match exactly the tutorial. Your copy sink seems to be correct but the file should have been created in "Customer" directory not the root of the container and naming has not taken effect.

**Comment by tanmoycuat** [comment]
Yes I checked it worked for me. However I had to create 2 different datasets. I work for customer data and other for dates. Somehow both are not working together but for a time being I can live with that. Thanks for your help.
