### ISSUE TITLE
Timeout occurred while using integration runtime

### ISSUE THREAD

**Issue by tanmoycuat** [Mmodarre/AzureDataFactoryHOL#14]
I found during integration runtime setup the region is selected as "Australia East".
When I tried using it later it gives time out. After modifying the region to "West US 2" it works fine.
This is just an observation if you think it might be due to other reasons you can skip.

![image](https://user-images.githubusercontent.com/47568628/82589551-efa45200-9bb9-11ea-90ef-f1be744d3ab0.png)

**Comment by Mmodarre** [comment]
Thanks for noting this. It may have been a capacity issue in the respective Azure region. Perhaps the instructions need to clearer on the fact that you could select any Azure region which is best suited your location and workload situation.

**Comment by tanmoycuat** [comment]
Ok great.

**Comment by aprasathbabu** [comment]
I tired these but i am still facing the same timed out error

**Comment by sushank143** [comment]
Even I am facing the same issue
