### ISSUE TITLE
Use managed Identity to access storage & SQL?

### ISSUE THREAD

**Issue by rajesh-ca** [Mmodarre/AzureDataFactoryHOL#17]
In the "02-Linked_Services_Datasets_and_Integration_Runtimes":

- instead of creating a KV secret with the storage account key, and accessing that secret via the ADF's Managed Identity, why not grant the ADF's Managed Identity Storage Blob Data Contributor access instead.

- similarly, for the Azure SQL instance as well, ADF managed identity could be used

Wouldn't this simplify the approach and also follow best practices - least privilege?

**Comment by Mmodarre** [comment]
Thanks for the suggestion. In the lab we were trying to show usage of AKV but probably. Perhaps we can add a note on using AAD MI as well. Would you have the spare time to add it to the lab?

**Comment by rajeshsam-ca** [comment]
Sure. I can add it to the lab.

**Comment by rajesh-ca** [comment]
While I was able to get this working with managed identities for both the storage account and Azure SQL, the setup for Azure SQL is a bit more complex. Since the focus is on ADF, I'm wondering if 
- it should be left as is (as AKV for both storage & SQL), or
- add Managed Identity for storage & leave Azure SQL as is (AKV), or
- add Managed Identity for both

Depending on the preference, the later steps would also need to change.

**Comment by Mmodarre** [comment]
I agree, the setup for SQL is much more complex. IMHO we add a note that AKV is not the only secure manner for authentication and MI can be setup but not get into details of how to. Perhaps links to documentation can also be added for further reading.

**Comment by rajesh-ca** [comment]
That makes sense. Do you want me to add that to the lab or will you?

**Comment by Mmodarre** [comment]
I'd appreciate it if you could add it.

**Comment by rajesh-ca** [comment]
Sure; will do.
