### ISSUE TITLE
Missing Auto-fill parameter steps in Execute Pipeline step

### ISSUE THREAD

**Issue by tanmoycuat** [Mmodarre/AzureDataFactoryHOL#18]
In Step 4. Lookup_activity_ForEach_loop_and_Execute_Pipeline_activity I couldn't find the auto-fill parameters as attached in the pic. Also in LookupDates settings, File path type  I need to set it to **Wildcard file path** instead of **File path in data set**
In case you feel something is wrong from my side, please ignore.
![image](https://user-images.githubusercontent.com/47568628/82643883-f79dd980-9c2d-11ea-9e0f-c7698532b9e6.png)

**Comment by Mmodarre** [comment]
Hi 
I am not entirely sure what is the issue here. Would you please elaborate on this so I can help resolve it.

**Comment by tanmoycuat** [comment]
I think I got this. I will close this it's not an issue.
