### ISSUE TITLE
Incorrect SQL Dataset being imported in SmartFoodFoodNutritionELT SCD 1 Instructions

### ISSUE THREAD

**Issue by mdrakiburrahman** [Mmodarre/AzureDataFactoryHOL#20]
Thank you for this wonderful lab.

I noticed in the instructions for loading up _food_nut.csv_ and _nutsDim.csv_ in [08-ELT_with_Mapping_Dataflows–Practice_excercises](https://github.com/Mmodarre/AzureDataFactoryHOL/blob/master/Lab-guide/08-ELT_with_Mapping_Dataflows%E2%80%93Practice_excercises/README.md) you are referencing bringing in [SmartFoodsDw][foodDim] throughout the tutorial:

![image](https://user-images.githubusercontent.com/46581776/82752521-a48e6880-9d8c-11ea-80e1-cab98fb42ca3.png)

I do understand that the item_id in _food_nut.csv_ corresponds to the sku in foodDim, in this case, perhaps it would be beneficial to specify that the initial foodDim import is for matching, whereas the sink should be foodNutDim?

Whereas there's no mention of importing [SmartFoodsDw][foodNutDim]:
![image](https://user-images.githubusercontent.com/46581776/82752533-b8d26580-9d8c-11ea-9893-9522cc637adf.png)

Since the content of those two csv's merges together to form foodNutDim.
![image](https://user-images.githubusercontent.com/46581776/82752577-fa631080-9d8c-11ea-91a6-236f66004ad8.png)

Thanks!

**Comment by Mmodarre** [comment]
For loading foodNutDim are reading from SmartFoodsDW.FoodDim to lookup the surrogate key of the currently active Food item. In the above screenshot the two stagings are from food_nut and nuts CSV files and the DB is for lookup to foodDim in database. 

The sink DB will be added last at the end of the tutorial and is called "DBSink"
